### ISSUE TITLE
RX580 not compatible with v11.3?

### ISSUE THREAD

**Issue by Huamaru** [nanopool/Claymore-XMR-Miner#26]
Hey I am currently trying to run the new v11.3 with 6 RX580s and for some reason it will either have all the cards fail, or only 3 of the 6 cards will work and then restart due to the watchdog. The rig works fine when mining Claymore Catalyst 11.5 for ethereum. Why is this different?

**Comment by OSCARGGO74** [comment]
Humaru

I ran a rig miner with 2 GPU Gigabyte Radeon RX 580 based on MoBo Gigabyte Z270SLI, 8 GB RAM DDR5 CL14; SSD 120 GB & CPU Intel i5@3Mhz. I use the Claymore v11.3, with add to hard fork monero announced on april 6Th 2018.

Greeting!

Oscar GGO

**Comment by Huamaru** [comment]
So I actually had a friend help me and we got it to work. The fix to this was to raise my computer's VIRTUAL MEMORY to 48000 (which is the total memory from all 6 cards x 8 gb).  This eventually allowed Claymore to run perfectly fine. I was previously using a VIRTUAL MEMORY of only 18k (3 x 6 cards because of what I read in a ether mining help guide) but those settings do not work for Claymore XMR! Thanks!
