### ISSUE TITLE
Crap software

### ISSUE THREAD

**Issue by jsteele84** [nanopool/Claymore-XMR-Miner#28]
Personally I just compile xmr stak with 0 dev fee and donte I honestly don’t trust anyone whom feels they have to force people to donate mining and make their miner in their own words work worse but still show the same hashrate just use a better all around miner without any of the problems I see this one having also it’s listed on minergate as a main miner so that should say something in itself seems like a very greedy developer

**Comment by sothcott** [comment]
Claymore more than makes up for in performance what it costs in dev fee.
